-- LOG PER LA VISTA MATERIALIZZATA
CREATE MATERIALIZED VIEW LOG ON VIAGGI
  WITH PRIMARY KEY, ROWID, SEQUENCE (SOMMAPREZZO, NUMEROBIGLIETTI)
  INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON TEMPO
  WITH PRIMARY KEY, ROWID, SEQUENCE (MESE, ANNO)
  INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON PERCORSO
  WITH PRIMARY KEY, ROWID, SEQUENCE(MODALITATRASPORTO)
  INCLUDING NEW VALUES;

-- VISTA MATERIALIZZATA

CREATE MATERIALIZED VIEW VM
BUILD IMMEDIATE
    REFRESH FAST ON COMMIT
    ENABLE QUERY REWRITE
AS 
	SELECT P.MODALITATRASPORTO, T.MESE, T.ANNO,
        SUM(V.NumeroBiglietti), 
        SUM(V.SommaPrezzo)
    FROM VIAGGI V, PERCORSO P, TEMPO T
    WHERE V.IDPERCORSO = P.IDPERCORSO AND V.IDTEMPO = T.IDTEMPO
    GROUP BY P.MODALITATRASPORTO, T.MESE, T.ANNO;

SELECT * FROM VM;

