-- QUERY 2.A

SELECT P.MODALITATRASPORTO, T.MESE, 
    SUM(NUMEROBIGLIETTI) AS BIGLIETTIVENDUTI,
    SUM(SUM(NUMEROBIGLIETTI)) OVER (PARTITION BY MODALITATRASPORTO ORDER BY MESE ROWS UNBOUNDED PRECEDING) AS SOMMACUMULATIVA,
    ROUND(SUM(NUMEROBIGLIETTI)*100.0/SUM(SUM(NUMEROBIGLIETTI)) OVER (PARTITION BY MESE),2) AS PERCENTUALEMESE
FROM VIAGGI V
JOIN PERCORSO P ON P.IDPERCORSO=V.IDPERCORSO
JOIN TEMPO T ON T.IDTEMPO=V.IDTEMPO
GROUP BY P.MODALITATRASPORTO, T.MESE
ORDER BY MESE, MODALITATRASPORTO;

-- QUERY 2.B

SELECT  CITTA, MODALITATRASPORTO, LINEA,
    ROUND(SUM(SOMMADURATA)/SUM(NUMEROBIGLIETTI), 2) AS DURATAMEDIA,
    SUM(SUM(SOMMAPREZZO)) OVER (PARTITION BY CITTA) AS RICAVITOTALI,
    ROUND(
    	SUM(SUM(SOMMAPREZZO)) OVER (PARTITION BY CITTA, MODALITATRASPORTO,LINEA)*100.0/ 
    	SUM(SUM(SOMMAPREZZO)) OVER (PARTITION BY CITTA,MODALITATRASPORTO),2) 
    AS PERCRICAVILINEE,
    RANK() OVER (PARTITION BY CITTA, MODALITATRASPORTO ORDER BY SUM(SOMMAPREZZO) DESC) AS CLASSIFICALINEE
FROM VIAGGI V
JOIN TEMPO T ON T.IDTEMPO=V.IDTEMPO
JOIN PERCORSO P ON P.IDPERCORSO=V.IDPERCORSO
JOIN LUOGO L ON L.IDLUOGO=V.IDLUOGO
WHERE T.ANNO>=2022
GROUP BY P.MODALITATRASPORTO, L.CITTA, P.LINEA
ORDER BY L.CITTA, P.MODALITATRASPORTO, PERCRICAVILINEE DESC
;